version: 1.0.0.{build}
branches:
  only:
  - master
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
build:
  project: src\Smartersoft.ExtendedPrincipals.sln
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: src\Smartersoft.ExtendedPrincipals\bin\Release\Smartersoft.ExtendedPrincipals.dll
  name: Smartersoft.ExtendedPrincipals.dll
- path: src\Smartersoft.ExtendedPrincipals\bin\Release\Smartersoft.ExtendedPrincipals.xml
  name: Smartersoft.ExtendedPrincipals.xml
- path: '**\Smartersoft.ExtendedPrincipals.*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: 0qbuPrrnu/qrD5eHEA3maAR7qt6Vg9oOfaoYtqWzcjZNSxoaZYqx+1gztJml805p
  skip_symbols: false
  artifact: /.*\.nupkg/